export enum EventType {
  ADMIN_SIGNIN = 'ADMIN_SIGNIN',

  CLIENT_SIGNIN = 'CLIENT_SIGNIN',
  CLIENT_SIGNUP = 'CLIENT_SIGNUP',

  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  USER_ACTIVATED = 'USER_ACTIVATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  USER_APPROVED = 'USER_APPROVED',
  USER_DISAPPROVED = 'USER_DISAPPROVED',

  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_DUPLICATE = 'ROLE_DUPLICATE',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',

  PERMISSION_CREATE = 'PERMISSION_CREATE',
  PERMISSION_DUPLICATE = 'PERMISSION_DUPLICATE',
  PERMISSION_UPDATE = 'PERMISSION_UPDATE',
  PERMISSION_DELETE = 'PERMISSION_DELETE',
}
